/**
 * Core amalgamation file for PHP extension build
 *
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 *
 * This file #includes all core translation units so that phpize sees a single
 * source file (core_amalgam.c → core_amalgam.o) with no ".." components in
 * the name.  The "#include" paths below use ".." which is fine for the C
 * preprocessor — only the source-file *name* passed to PHP_NEW_EXTENSION must
 * be free of ".." components.
 *
 * Include paths are relative to this file's directory (bindings/php/).
 *
 * Generated by: dev/generate_amalgam.sh
 */

/* Include the generated config header from the build directory for feature
 * flags.  On Windows the PHP SDK emits config.w32.h; on every other platform
 * it is config.h.  _WIN32/_WIN64 are compiler built-ins, so they are visible
 * here even before any PHP header has been included. */
#if defined(_WIN32) || defined(_WIN64)
#include "config.w32.h"
#else
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif
#endif

/* Include all core source files */
#include "../../core/src/lexer.c"
#include "../../core/src/parser.c"
#include "../../core/src/ast.c"
#include "../../core/src/compiler.c"
#include "../../core/src/vm.c"
#include "../../core/src/table.c"
#include "../../core/src/array.c"
#include "../../core/src/dynamic_pattern.c"
#include "../../core/src/version.c"
#include "../../core/src/unicode_fold.c"
#include "../../core/src/string_fn.c"
#include "../../core/src/type_fn.c"
#include "../../core/src/pattern_build.c"
#include "../../core/src/search.c"
#include "../../core/src/search_simd.c"
#include "../../core/src/api.c"

