#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>

#define MAX_PAIRS 4096

typedef struct {
    unsigned long lower;
    unsigned long upper[8];
    int           upper_len;
} FoldEntry;

static FoldEntry by_code[MAX_PAIRS];   /* UCD code → mapping */
static int n_by_code = 0;

static FoldEntry by_map[MAX_PAIRS];    /* mapping → code (inverse) */
static int n_by_map = 0;

static FoldEntry multi_entries[64];
static int n_multi = 0;

static int seen_upper[256];            /* bitmap to dedup inverse entries in U+0000–U+00FF range */

static char *trim(char *s) {
    while (*s && isspace((unsigned char)*s)) s++;
    if (*s == 0) return s;
    char *end = s + strlen(s) - 1;
    while (end > s && isspace((unsigned char)*end)) end--;
    *(end + 1) = 0;
    return s;
}

static void parse_line(char *line) {
    char *p = trim(line);
    if (*p == 0 || *p == '#') return;

    char *code_str = strtok(p, ";");
    if (!code_str) return;
    char *status = strtok(NULL, ";");
    if (!status) return;
    char *mapping = strtok(NULL, ";");
    if (!mapping) return;

    if (status[0] == 'T') return;

    unsigned long cp = strtoul(code_str, NULL, 16);
    if (cp > 0xFFFF) return;

    unsigned long uppers[8];
    int n_up = 0;
    char *map_trim = trim(mapping);
    char *tok = strtok(map_trim, " \t");
    while (tok && n_up < 8) {
        uppers[n_up++] = strtoul(tok, NULL, 16);
        tok = strtok(NULL, " \t");
    }
    if (n_up == 0) return;

    /* Multi-char expansion */
    if (n_up > 1) {
        if (n_multi < 64) {
            multi_entries[n_multi].lower = cp;
            multi_entries[n_multi].upper_len = n_up;
            /* Uppercase each expansion codepoint (UCD gives lowercase fold) */
            for (int i = 0; i < n_up && i < 8; i++) {
                unsigned long c = uppers[i];
                if (c >= 'a' && c <= 'z')
                    c = c - 32;
                multi_entries[n_multi].upper[i] = c;
            }
            n_multi++;
        }
        return;
    }

    /* Skip identity (mapping == code) for C/S status */
    if (uppers[0] == cp) return;

    /* Forward: code → mapping (uppercase → lowercase) */
    if (n_by_code < MAX_PAIRS) {
        by_code[n_by_code].lower = cp;
        by_code[n_by_code].upper[0] = uppers[0];
        by_code[n_by_code].upper_len = 1;
        n_by_code++;
    }

    /* Inverse: mapping → code (lowercase → uppercase) */
    /* Skip if we already have an entry for this mapping in Latin-1 range */
    unsigned long lower_cp = uppers[0];
    if (lower_cp <= 0xFF) {
        if (seen_upper[lower_cp]) return;
        seen_upper[lower_cp] = 1;
    }

    if (n_by_map < MAX_PAIRS) {
        by_map[n_by_map].lower = lower_cp;
        by_map[n_by_map].upper[0] = cp;
        by_map[n_by_map].upper_len = 1;
        n_by_map++;
    }
}

static int cmp_by_lower(const void *a, const void *b) {
    const FoldEntry *ea = (const FoldEntry *)a;
    const FoldEntry *eb = (const FoldEntry *)b;
    if (ea->lower < eb->lower) return -1;
    if (ea->lower > eb->lower) return 1;
    return 0;
}

int main(int argc, char **argv) {
    const char *ucd_path = "CaseFolding.txt";
    int need_fetch = 1;

    if (argc > 1) {
        ucd_path = argv[1];
        need_fetch = 0;
    }

    if (need_fetch) {
        FILE *f = fopen(ucd_path, "r");
        if (f) {
            fclose(f);
        } else {
            fprintf(stderr, "info: downloading CaseFolding.txt from unicode.org...\n");
            char cmd[4096];
            snprintf(cmd, sizeof(cmd),
                     "curl -s -o \"%s\" \"%s\"",
                     ucd_path,
                     "https://unicode.org/Public/UCD/latest/ucd/CaseFolding.txt");
            int ret = system(cmd);
            if (ret != 0) { fprintf(stderr, "error: curl failed\n"); return 1; }
        }
    }

    FILE *f = fopen(ucd_path, "r");
    if (!f) { fprintf(stderr, "error: cannot open '%s'\n", ucd_path); return 1; }

    char line[4096];
    while (fgets(line, sizeof(line), f)) parse_line(line);
    fclose(f);

    fprintf(stderr, "info: %d forward pairs, %d inverse pairs, %d multi-char\n",
            n_by_code, n_by_map, n_multi);

    qsort(by_code, n_by_code, sizeof(FoldEntry), cmp_by_lower);
    qsort(by_map,  n_by_map,  sizeof(FoldEntry), cmp_by_lower);

    /* Emit */
    printf("/**\n");
    printf(" * @file unicode_fold_data.c\n");
    printf(" * @brief Auto-generated BMP case folding tables\n");
    printf(" *\n");
    printf(" * Generated by dev/gen_unicode_fold.c from Unicode CaseFolding.txt.\n");
    printf(" * Do not edit by hand. Regenerate with: make gen-unicode-fold\n");
    printf(" */\n\n");
    printf("#include <stdint.h>\n");
    printf("#include <stddef.h>\n\n");
    printf("typedef struct { uint32_t lower; uint32_t upper; } FoldPair;\n\n");

    /* BMP_UPPER_TO_LOWER: sorted by .lower (uppercase), binary search for snobol_to_lower_cp */
    printf("static const FoldPair BMP_UPPER_TO_LOWER[] = {\n");
    for (int i = 0; i < n_by_code; i++) {
        printf("    { 0x%04lX, 0x%04lX },\n",
               by_code[i].lower, by_code[i].upper[0]);
    }
    printf("};\n");
    printf("static const size_t N_BMP_UPPER_TO_LOWER ="
           " sizeof(BMP_UPPER_TO_LOWER) / sizeof(BMP_UPPER_TO_LOWER[0]);\n\n");

    /* BMP_LOWER_TO_UPPER: sorted by .lower (lowercase), binary search for snobol_to_upper_cp */
    printf("static const FoldPair BMP_LOWER_TO_UPPER[] = {\n");
    for (int i = 0; i < n_by_map; i++) {
        printf("    { 0x%04lX, 0x%04lX },\n",
               by_map[i].lower, by_map[i].upper[0]);
    }
    printf("};\n");
    printf("static const size_t N_BMP_LOWER_TO_UPPER ="
           " sizeof(BMP_LOWER_TO_UPPER) / sizeof(BMP_LOWER_TO_UPPER[0]);\n\n");

    /* Multi-char expansion table */
    printf("typedef struct {\n");
    printf("    uint32_t lower;\n");
    printf("    uint32_t upper[2];\n");
    printf("    int      len;\n");
    printf("} MultiCharExpansion;\n\n");

    printf("static const MultiCharExpansion MULTI_CHAR_EXPANSIONS[] = {\n");
    for (int i = 0; i < n_multi; i++) {
        printf("    { 0x%04lX, { ", multi_entries[i].lower);
        int n = multi_entries[i].upper_len;
        if (n > 2) n = 2;
        for (int k = 0; k < n; k++) {
            if (k > 0) printf(", ");
            printf("0x%04lX", multi_entries[i].upper[k]);
        }
        for (int k = n; k < 2; k++) {
            if (k > 0) printf(", ");
            printf("0x0000");
        }
        printf(" }, %d },\n", n);
    }
    printf("};\n");
    printf("static const size_t N_MULTI_CHAR ="
           " sizeof(MULTI_CHAR_EXPANSIONS)"
           " / sizeof(MULTI_CHAR_EXPANSIONS[0]);\n\n");

    return 0;
}
