#!/bin/bash
#
# generate_amalgam.sh - Generate or verify core_amalgam.c
#
# Usage:
#   ./dev/generate_amalgam.sh generate  - Regenerate core_amalgam.c
#   ./dev/generate_amalgam.sh verify    - Check if core_amalgam.c is up to date
#
# This script ensures the PHP binding's amalgamation file includes all
# core source files in the correct order.
#

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
CORE_SRC="$PROJECT_ROOT/core/src"
AMALGAM_FILE="$PROJECT_ROOT/bindings/php/core_amalgam.c"

# Core source files in dependency order
# This order matters! Files must be included after their dependencies.
CORE_FILES=(
    "lexer.c"
    "parser.c"
    "ast.c"
    "compiler.c"
    "vm.c"
    "table.c"
    "dynamic_pattern.c"
    "jit.c"
    "version.c"
)

# Header for the amalgamation file
read -r -d '' AMALGAM_HEADER << 'EOF' || true
/**
 * Core amalgamation file for PHP extension build
 *
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 *
 * This file #includes all core translation units so that phpize sees a single
 * source file (core_amalgam.c → core_amalgam.o) with no ".." components in
 * the name.  The "#include" paths below use ".." which is fine for the C
 * preprocessor — only the source-file *name* passed to PHP_NEW_EXTENSION must
 * be free of ".." components.
 *
 * Include paths are relative to this file's directory (bindings/php/).
 *
 * Generated by: dev/generate_amalgam.sh
 */

/* Include config.h from the build directory for feature flags */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

/* Include all core source files */
EOF

generate_amalgam() {
    echo "🔨 Generating core_amalgam.c..."
    
    # Start with the header
    echo "$AMALGAM_HEADER" > "$AMALGAM_FILE"
    
    # Add includes for each core file
    for file in "${CORE_FILES[@]}"; do
        if [ -f "$CORE_SRC/$file" ]; then
            echo "#include \"../../core/src/$file\"" >> "$AMALGAM_FILE"
        else
            echo "❌ Warning: Core source file not found: $file" >&2
        fi
    done
    
    # Add final newline
    echo "" >> "$AMALGAM_FILE"
    
    echo "✅ Generated $AMALGAM_FILE"
    echo "   Included ${#CORE_FILES[@]} core source files"
}

verify_amalgam() {
    echo "🔍 Verifying core_amalgam.c..."
    
    local errors=0
    local missing_files=()
    local extra_includes=()
    
    # Check that all required files are included
    for file in "${CORE_FILES[@]}"; do
        if ! grep -q "#include.*$file" "$AMALGAM_FILE"; then
            missing_files+=("$file")
            errors=$((errors + 1))
        fi
    done
    
    # Check for any includes that shouldn't be there
    while IFS= read -r line; do
        # Extract filename from #include line
        if [[ "$line" =~ ^#include.*\"../../core/src/([^\"]+)\" ]]; then
            included_file="${BASH_REMATCH[1]}"
            # Check if this file is in our expected list
            local found=0
            for expected in "${CORE_FILES[@]}"; do
                if [ "$included_file" = "$expected" ]; then
                    found=1
                    break
                fi
            done
            if [ $found -eq 0 ]; then
                extra_includes+=("$included_file")
                errors=$((errors + 1))
            fi
        fi
    done < "$AMALGAM_FILE"
    
    # Report results
    if [ $errors -gt 0 ]; then
        echo "❌ Verification FAILED with $errors error(s):"
        
        if [ ${#missing_files[@]} -gt 0 ]; then
            echo ""
            echo "   Missing includes:"
            for file in "${missing_files[@]}"; do
                echo "     - $file"
            done
        fi
        
        if [ ${#extra_includes[@]} -gt 0 ]; then
            echo ""
            echo "   Extra/unexpected includes:"
            for file in "${extra_includes[@]}"; do
                echo "     - $file"
            done
        fi
        
        echo ""
        echo "   Run './dev/generate_amalgam.sh generate' to regenerate"
        exit 1
    else
        echo "✅ Verification PASSED"
        echo "   All ${#CORE_FILES[@]} core source files are properly included"
        exit 0
    fi
}

# Show usage if no argument provided
if [ $# -eq 0 ]; then
    echo "Usage: $0 {generate|verify}"
    echo ""
    echo "Commands:"
    echo "  generate  - Regenerate core_amalgam.c from core/src/*.c"
    echo "  verify    - Check if core_amalgam.c is up to date"
    exit 1
fi

case "${1:-}" in
    generate)
        generate_amalgam
        ;;
    verify)
        verify_amalgam
        ;;
    *)
        echo "❌ Unknown command: $1"
        echo "Usage: $0 {generate|verify}"
        exit 1
        ;;
esac
