#!/bin/bash
#
# generate_amalgam.sh - Generate or verify core_amalgam.c
#
# Usage:
#   ./dev/generate_amalgam.sh generate  - Regenerate core_amalgam.c
#   ./dev/generate_amalgam.sh verify    - Check if core_amalgam.c is up to date
#
# This script ensures the PHP binding's amalgamation file includes all
# core source files in the correct order.
#

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Ensure the generated version.h exists (it is needed by the core headers the
# amalgam includes). Single source of truth stays the top-level CMakeLists.txt.
if [ -x "$SCRIPT_DIR/generate_version_header.sh" ]; then
  bash "$SCRIPT_DIR/generate_version_header.sh" >&2 || true
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
CORE_SRC="$PROJECT_ROOT/core/src"
DEPS_SLJIT="$PROJECT_ROOT/deps/sljit"
AMALGAM_FILE="$PROJECT_ROOT/bindings/php/core_amalgam.c"

# Core source files in dependency order
# This order matters! Files must be included after their dependencies.
CORE_FILES=(
    "lexer.c"
    "parser.c"
    "ast.c"
    "compiler.c"
    "compiler_analysis.c"
    "compiler_codegen.c"
    "vm_choice.c"
    "vm_capture.c"
    "vm_exec.c"
    "table.c"
    "array.c"
    "dynamic_pattern.c"
    "version.c"
    "unicode_fold.c"
    "string_fn.c"
    "type_fn.c"
    "pattern_build.c"
    "search_meta.c"
    "search_tiers.c"
    "search_simd.c"
    "api.c"
)

# Dependency source files (outside core/src/)
DEPS_FILES=()

# Header for the amalgamation file
read -r -d '' AMALGAM_HEADER << 'EOF' || true
/**
 * Core amalgamation file for PHP extension build
 *
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 *
 * This file #includes all core translation units so that phpize sees a single
 * source file (core_amalgam.c → core_amalgam.o) with no ".." components in
 * the name.  The "#include" paths below use ".." which is fine for the C
 * preprocessor — only the source-file *name* passed to PHP_NEW_EXTENSION must
 * be free of ".." components.
 *
 * Include paths are relative to this file's directory (bindings/php/).
 *
 * Generated by: dev/generate_amalgam.sh
 */

/* Include the generated config header from the build directory for feature
 * flags.  On Windows the PHP SDK emits config.w32.h; on every other platform
 * it is config.h.  _WIN32/_WIN64 are compiler built-ins, so they are visible
 * here even before any PHP header has been included. */
#if defined(_WIN32) || defined(_WIN64)
#include "config.w32.h"
#else
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif
#endif

/* Include all core source files */
EOF

generate_amalgam() {
    echo "🔨 Generating core_amalgam.c..."
    
    # Start with the header
    echo "$AMALGAM_HEADER" > "$AMALGAM_FILE"
    
    # Add includes for each core file
    for file in "${CORE_FILES[@]}"; do
        if [ -f "$CORE_SRC/$file" ]; then
            echo "#include \"../../core/src/$file\"" >> "$AMALGAM_FILE"
        else
            echo "❌ Warning: Core source file not found: $file" >&2
        fi
    done
    
    # Add includes for each dependency file
    for file in "${DEPS_FILES[@]+"${DEPS_FILES[@]}"}"; do
        if [ -f "$DEPS_SLJIT/$file" ]; then
            echo "#include \"../../deps/sljit/$file\"" >> "$AMALGAM_FILE"
        else
            echo "❌ Warning: Dependency source file not found: $file" >&2
        fi
    done
    
    # Add final newline
    echo "" >> "$AMALGAM_FILE"
    
    core_count=${#CORE_FILES[@]}
    deps_count=${#DEPS_FILES[@]}
    total=$(( core_count + deps_count ))
    echo "✅ Generated $AMALGAM_FILE"
    if [ "$deps_count" -gt 0 ]; then
        echo "   Included $total source files ($core_count core + $deps_count deps)"
    else
        echo "   Included $total source files ($core_count core)"
    fi
}

verify_amalgam() {
    echo "🔍 Verifying core_amalgam.c..."
    
    local errors=0
    local missing_files=()
    local extra_includes=()
    
    # Merge all expected files
    local expected_files=("${CORE_FILES[@]}" ${DEPS_FILES[@]+"${DEPS_FILES[@]}"})
    
    # Check that all required files are included
    for file in "${expected_files[@]}"; do
        if ! grep -q "#include.*$file" "$AMALGAM_FILE"; then
            missing_files+=("$file")
            errors=$((errors + 1))
        fi
    done
    
    # Check for any includes that shouldn't be there
    while IFS= read -r line; do
        # Extract filename from #include line
        local included_file=""
        if [[ "$line" =~ ^#include.*\"../../core/src/([^\"]+)\" ]]; then
            included_file="${BASH_REMATCH[1]}"
        elif [[ "$line" =~ ^#include.*\"../../deps/sljit/([^\"]+)\" ]]; then
            included_file="${BASH_REMATCH[1]}"
        fi
        if [ -n "$included_file" ]; then
            # Check if this file is in our expected list
            local found=0
            for expected in "${expected_files[@]}"; do
                if [ "$included_file" = "$expected" ]; then
                    found=1
                    break
                fi
            done
            if [ $found -eq 0 ]; then
                extra_includes+=("$included_file")
                errors=$((errors + 1))
            fi
        fi
    done < "$AMALGAM_FILE"
    
    # Report results
    if [ $errors -gt 0 ]; then
        echo "❌ Verification FAILED with $errors error(s):"
        
        mf_len=${#missing_files[@]+${#missing_files[@]}}; mf_len=${mf_len:-0}
        if [ "$mf_len" -gt 0 ]; then
            echo ""
            echo "   Missing includes:"
            for file in "${missing_files[@]}"; do
                echo "     - $file"
            done
        fi
        
        if [ ${#extra_includes[@]} -gt 0 ]; then
            echo ""
            echo "   Extra/unexpected includes:"
            for file in "${extra_includes[@]}"; do
                echo "     - $file"
            done
        fi
        
        echo ""
        echo "   Run './dev/generate_amalgam.sh generate' to regenerate"
        exit 1
    else
        echo "✅ Verification PASSED"
        echo "   All ${#CORE_FILES[@]} core source files are properly included"
        exit 0
    fi
}

# Show usage if no argument provided
if [ $# -eq 0 ]; then
    echo "Usage: $0 {generate|verify}"
    echo ""
    echo "Commands:"
    echo "  generate  - Regenerate core_amalgam.c from core/src/*.c"
    echo "  verify    - Check if core_amalgam.c is up to date"
    exit 1
fi

case "${1:-}" in
    generate)
        generate_amalgam
        ;;
    verify)
        verify_amalgam
        ;;
    *)
        echo "❌ Unknown command: $1"
        echo "Usage: $0 {generate|verify}"
        exit 1
        ;;
esac
